version: 1.0.{build}
install:
- cmd: >-
    set PATH=C:\Python36;C:\Python36\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin

    pip install -e .[dev,qt5]

    python tools\build\prep_windows

    choco install -y nsis.portable -version 2.50
build_script:
- cmd: >-
    python setup.py build

    build\exe.win32-3.6\cfclient.exe --check-imports

    python win32install\generate_nsis.py

    makensis win32install\cfclient.nsi
artifacts:
- path: win32install\*.exe
